name: Release
on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build check --stacktrace --parallel
        env:
          ACTIONS_REF: ${{ github.ref }}
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./build/libs/

      - name: Gradle Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish publishToSonatype closeSonatypeStagingRepository --stacktrace
        env:
          ACTIONS_REF: ${{ github.ref }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.MAVEN_CENTRAL_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_CENTRAL_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_PGP_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PGP_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PGP_PASSWORD }}
